url: https://kwyau126.github.io
baseurl: "/"

# Site settings
title: MSc Cyber Security
email: kwyau126@yahoo.com.hk
description: "MY E-PORTFOLIO BASED ON THE WORK CARRIED OUT ON THE MSC CYBER SECURITy PROGRAMME."


# Team names, titles and social links
people:
- name: Kwok Wai Yau
  pic:
  position: 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: LinkedIn
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/kwok.wai.yau
  - title: linkedin
    url: https://www.linkedin.com/in/kwok-wai-yau-27051629
  - title: github
    url: https://kwyau126.github.io/e-portfolio/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
